[package]
name = "mysql2sqlite"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
log = "0.4"
fern = "0.7.1"
chrono = "0.4"
env_logger = "0.11.8"
mysql = "26.0.0"
rusqlite = { version = "0.37.0", features = ["bundled"] }
serde_json = "1"
